language: python
python:
  - '2.7'
  - '3.3'

install:
  - 'travis_retry pip install -q -e ".[test]"'
  - 'travis_retry pip install coveralls'

script: 'py.test --pep8 --cov scim'

after_success: 'coveralls'
